# travis config

language: r

cache: packages

os:
  - linux
#  - osx

r_github_packages:
  - jimhester/covr
  - jakobbossek/ecr2

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
    on_success: change
    on_failure: always
